### ISSUE TITLE
Passing query params makes requests bypass the auth check

### ISSUE THREAD

**Issue by dklymenk** [SoftwareBrothers/adminjs-expressjs#80]
**Describe the bug**
Providing any valid query param combination, allows users to bypass the cookie check

**Installed libraries and their versions**
* adminjs@5.10.0
* @adminjs/express@4.1.0
* @adminjs/nestjs@4.0.1
* @adminjs/prisma@1.0.3

**To Reproduce**
1. Have an admin with required authentication
1. Log in
2. Navigate to any resource
3. Apply any filter
4. Bookmark the page or copy the URL with query params
5. Either log out or open a new tab in incognito mode
6. Go to saved URL with query params
7. You will see the entities

**Expected behavior**
You should be redirected to the login page

**Comment by dziraf** [comment]
I'll try to fix this ASAP (probably tomorrow). If this is critical for you, you can in the meantime create an express middleware to protect your admin router

**Comment by dklymenk** [comment]
I am not sure if I am doing something wrong, but I have updated to 4.1.1 and now applying any query param via UI (sort or filter by field) throws this alert and logs me out.
![DeepinScreenshot_select-area_20220512125000](https://user-images.githubusercontent.com/64093836/168043429-0f784809-a8eb-4f59-89b1-dc0d276e7768.png)

Seems like a regression from #81

**Comment by dziraf** [comment]
@dklymenk can you show how your url is structured? I've just retested and `http://localhost:3000/resources/cases?filters.sex=male&page=1` works for me

**Comment by dklymenk** [comment]
Example URL I get when clicking on description field: http://localhost:3000/admin/resources/Report?direction=asc&sortBy=description
Example URL I get when applying a filter: http://localhost:3000/admin/resources/Report?filters.status=UPLOADED&page=1

**Comment by dklymenk** [comment]
Yeah, it seems not to be the case if set `rootPath` to `/`. Only when I set it back to `/admin` I get this behaviour.

**Comment by dziraf** [comment]
I've just released another version and added an additional unit test for a different root path, can you take a look?

**Comment by dklymenk** [comment]
Everything seems to be working correctly now.

Thank you for the fix. And thank you for this project.

**Comment by dziraf** [comment]
You're welcome. Just leaving one extra note for if you want to extend AdminJS router with extra endpoints in the future.

Currently, if you added a custom endpoint, the middleware would return a redirect to the `loginPath`. If you want to add custom routes, you might have to modify your setup a bit. In my case I have a `/refresh` endpoint for refreshing a session with external API service. In order to make it work but also have access to user's session I have to create express router manually and pass it to `buildAuthenticatedRouter`:

```
  const ConnectSession = ConnectPgSimple(session);

  const sessionStore = new ConnectSession({
    conObject: {
      database: config.db.database,
      host: config.db.host,
      port: config.db.port,
      user: config.db.username,
      password: config.db.password,
      ssl: config.db.ssl,
    },
    tableName: 'session',
  });

  const sessionOptions = {
    store: sessionStore,
    cookie: {
      httpOnly: config.session.httpOnly,
      secure: config.session.secure,
    },
    saveUninitialized: config.session.saveUninitialized,
    resave: config.session.resave,
    unset: config.session.unset,
    secret: config.session.cookiePassword,
    name: config.session.cookieName,
  };

  const router = express.Router();
  router.use(session(sessionOptions));
  router.get('/refresh', refresh);

  AdminJSExpress.buildAuthenticatedRouter(adminJs as any, {
    cookieName: config.session.cookieName,
    cookiePassword: config.session.cookiePassword,
    authenticate,
  }, router, sessionOptions);

  app.use(adminOptions.rootPath ?? '/admin', router);
```
